export const theme = {
  colors: {
    primary:      "#7966fc",
    primaryLight: "#f0eeff",
    primaryDark:  "#5a4ddb",
    secondary:    "#fa6bae",
    open:         "#22C55E",
    closed:       "#9CA3AF",
    surface:      "#fdfdfb",
    background:   "#f5f4f9",
    border:       "#ece9f0",
    text:         "#1a1625",
    muted:        "#8b859e",
    danger:       "#EF4444",
  },
  dark: {
    colors: {
      primary:      "#9b8fff",
      primaryLight: "#2d2650",
      primaryDark:  "#7966fc",
      secondary:    "#f891c3",
      open:         "#4ade80",
      closed:       "#6b7280",
      surface:      "#454b57",
      background:   "#393f4a",
      border:       "#525866",
      text:         "#f8f7f2",
      muted:        "#a8a4b8",
      danger:       "#EF4444",
    },
  },
  radius: {
    card:  "12px",
    pill:  "999px",
    input: "8px",
  },
  font: {
    sans: "'DM Sans', system-ui, sans-serif",
  },
};
